---
# Installing the required Kali Linux, Python and Ruby packages
- name: Install Kali packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Remove Kali packages
  ansible.builtin.apt:
    name: "{{ removes }}"
    state: purge

- name: Install Ruby Gem Packages
  community.general.gem:
    name: "{{ item }}"
    state: latest
    user_install: false
  loop: "{{ ruby_gem_packages }}"
