---
# Installing the required Kali Linux, Python and Ruby packages
#- name: Install Kali packages
#  ansible.builtin.apt:
#    name: "{{ packages }}"
#    state: present

- name: Install Python Pip Packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  loop: "{{ python_pip_packages }}"

- name: Install Ruby Gem Packages
  community.general.gem:
    name: "{{ item }}"
    state: latest
    user_install: false
  loop: "{{ ruby_gem_packages }}"