---
# Deploy tools not found in the Kali repositories
# Install AutoRecon
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

# Create folder Tools 
- name: Create Tools folder in $HOME  
  ansible.builtin.file:
      dest: "/home/{{ user }}/Tools"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}" 
      mode: 0700

### AUTORECON
- name: Copy AutoRecon from repository
  git:
    repo: https://github.com/Tib3rius/AutoRecon
    dest: /home/{{ user}}/Tools/autorecon
    update: yes
    force: yes

- name: Install AutoRecon Requirements
  pip:
    executable: pip3
    requirements: /home/{{ user}}/Tools/autorecon/requirements.txt

- name: Install pipx - Pt. 1
  ansible.builtin.shell: python3 -m pip install --user pipx
  become: true
  become_user: "{{user}}"
  args:
    executable: /bin/bash

- name: Install pipx - Pt. 2
  ansible.builtin.shell: python3 -m pipx ensurepath
  become: true
  become_user: "{{user}}"
  args:
    executable: /bin/bash

- name: Install pipx - Pt. 3
  ansible.builtin.shell: pipx install pipx
  become: true
  become_user: "{{user}}"
  args:
    executable: /bin/bash

- name: Resource bashrc
  ansible.builtin.shell: source /home/{{user}}/.bashrc
  become: true
  become_user: "{{user}}"
  args:
    executable: /bin/bash

- name: Install Autorecon via pipx - Root
  ansible.builtin.shell: /home/{{user}}/.local/bin/pipx install git+https://github.com/Tib3rius/AutoRecon.git

- name: Install AutoRecon via pipx - User
  become: true
  become_user: "{{user}}"
  ansible.builtin.shell: /home/{{user}}/.local/bin/pipx install git+https://github.com/Tib3rius/AutoRecon.git

  
# Install VScode
- name: Add Microsofts PGP key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: Add VS Code repository
  copy:
    content: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    dest: "/etc/apt/sources.list.d/vscode.list"
  become: yes
- name: Install VScode
  apt:
    name: code
    state: present
    update_cache: yes
      

# Clone git repos
- name: clone git repositories, download files and create directory structure
  block:
  - name: Clone git repositories
    become: true
    become_user: "{{ user }}"
    ansible.builtin.git:
      repo: "{{ item.repo }}"
      dest: "/home/{{ user }}/{{ item.path }}"
      version: "{{ item.version | default('main') }}"
      depth: 1
      force: true
    loop: "{{ git_repos | flatten(levels=1) }}"