---
# Deploy tools not found in the Kali repositories
# Install AutoRecon
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

# Clone git repos
- name: Clone git repositories, download files and create directory structure
  block:
  - name: Clone git repositories
    become: true
    become_user: "{{ user }}"
    ansible.builtin.git:
      repo: "{{ item.repo }}"
      dest: "/home/{{ user }}/{{ item.path }}"
      version: "{{ item.version | default('master') }}"
      depth: 1
      force: true
    loop: "{{ git_repos | flatten(levels=1) }}"
      
# Install via poetry
- name: Install applicable Git repos in virtual environment via poetry
  block:
  - name: Install {{ item.repo }} with poetry
    ansible.builtin.shell: 
      cmd: poetry install
      chdir: "/home/{{ user }}/{{ item.path }}"
      executable: /bin/bash
    loop: "{{ git_repos | flatten(levels=1) }}"
    when: item.install_with_poetry is defined
    become: true
    become_user: "{{ user }}"