---
# Clone own config repo 
- name: Git clone own configs
  git:
    repo: https://github.com/4Kp3n/configs.git
    dest: /home/{{user}}/Setup/configs
    depth: 1
    update: yes
    force: yes
      
# Setup Oh My Zsh
- name: Git clone Oh My Zsh 
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/{{user}}/Setup/ohmyzsh
    depth: 1
    update: yes
    force: yes

- name: Add aliase to zshrc
  ansible.builtin.shell: /home/{{user}}/Setup/ohmyzsh/tools/install.sh
  become: true
  become_user: "{{ user }}"

#- name: Creates directory for nvim
#  file:
#    path: /home/{{user}}/.local/share/nvim/view
#    state: directory
#    owner: www-data
#    group: www-data
#    mode: 0775
#    recurse: yes
#    

# Clone personal arsenal repo
- name: Git clone own arsenal fork
  git:
    repo: https://github.com/4Kp3n/arsenal.git
    dest: /opt/arsenal
    depth: 1
    update: yes
    force: yes


# Setup neovim with Vundle as plugin manager
- name: Git clone Vundle 
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: /home/{{user}}/.config/nvim/bundle/Vundle.vim
    depth: 1
    update: yes
    force: yes

- name: Copy vim config
  ansible.builtin.copy:
    src: /home/{{user}}/Setup/configs/init.vim
    dest: /home/{{user}}/.config/nvim/init.vim
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Install vim plugins 
  ansible.builtin.shell: nvim +PluginInstall +qall
  become: true
  become_user: "{{ user }}"

# Copy zshrc files
- name: Copy zshrc
  ansible.builtin.copy:
    src: /home/{{user}}/Setup/configs/zshrc
    dest: /home/{{user}}/.zshrc
    owner: "{{ user }}"
    group: "{{ user }}"
- name: Copy p10k.zshrc
  ansible.builtin.copy:
    src: /home/{{user}}/Setup/configs/p10k.zsh
    dest: /home/{{user}}/.p10k.zsh
    owner: "{{ user }}"
    group: "{{ user }}"


# Take care of aliase
- name: Copy aliase
  ansible.builtin.copy:
    src: /home/{{user}}/Setup/configs/kali-aliase
    dest: /home/{{user}}/.aliase
    owner: "{{ user }}"
    group: "{{ user }}"


# Change tmux config
- name: Change tmux config
  ansible.builtin.copy:
    src: /home/{{user}}/Setup/configs/tmux.conf
    dest: /home/{{user}}/.tmux.conf
    owner: "{{ user }}"
    group: "{{ user }}"
