---

- name: Copy vim config for kali
  ansible.builtin.copy:
    src: /home/{{user}}/Setup/configs/init.vim
    dest: /home/{{user}}/.config/nvim/init.vim
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Install vim plugins 
  ansible.builtin.shell: nvim +PluginInstall +qall
  become: true
  become_user: "{{ user }}"

# Copy zshrc files
- name: Copy zshrc for kali
  ansible.builtin.copy:
    src: /home/{{user}}/Setup/configs/zshrc
    dest: /home/{{user}}/.zshrc
    owner: "{{ user }}"
    group: "{{ user }}"
- name: Copy p10k.zshrc for kali
  ansible.builtin.copy:
    src: /home/{{user}}/Setup/configs/p10k.zsh
    dest: /home/{{user}}/.p10k.zsh
    owner: "{{ user }}"
    group: "{{ user }}"

# Copy aliase
- name: Copy user aliase
  ansible.builtin.copy:
    src: /home/{{user}}/Setup/configs/kali-aliase
    dest: /home/{{user}}/.aliase
    owner: "{{ user }}"
    group: "{{ user }}"

# Copy tmux config
- name: Change tmux config
  ansible.builtin.copy:
    src: /home/{{user}}/Setup/configs/tmux.conf
    dest: /home/{{user}}/.tmux.conf
    owner: "{{ user }}"
    group: "{{ user }}"

# Copy xfce4-power-manager.xml to disable screen lock
- name: Copy xfce4-power-manager.xml
  ansible.builtin.copy:
    src: /home/{{user}}/Setup/configs/xfce4-power-manager.xml
    dest: /home/{{user}}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
    owner: "{{ user }}"
    group: "{{ user }}"