---
- name: Enable SSH service
  ansible.builtin.service:
    name: ssh
    enabled: yes

- name: Start docker service
  ansible.builtin.service:
    name: docker
    state: started

# Clean the system
- name: Remove unnecessary packages
  ansible.builtin.apt:
    autoremove: true

- name: Clean apt cache
  ansible.builtin.apt:
    autoclean: true
      
- name: Remove unwanted folders
  ansible.builtin.shell: rm -rf /home/{{ user }}/Documents /home/{{ user }}/Music /home/{{ user }}/Pictures /home/{{ user }}/Public /home/{{ user }}/Templates /home/{{ user }}/Videos