---
# tasks file for configuring Kali Linux
- name: Install all packages
  import_tasks: 0-packages.yml
  become: true
  when: kali_packages == true

- name: Install all tools
  import_tasks: 1-tools.yml
  become: true
  when: kali_tools == true

- name: Configure the system
  import_tasks: 2-config.yml
  become: true
  when: kali_config == true

- name: Finalize the configuration
  import_tasks: 3-post-configuration.yml
  become: true
  when: post_configuration == true
